apiVersion: apps/v1
kind: Deployment
metadata: 
  name: next-app
  labels: 
     app: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-app
        image: "ghcr.io/161275/my-next-app:latest"
        ports:
        - containerPort: 3000

