nextapp:
  deployment:
    replicas: 2
    image: 
      repository: "ghcr.io/161275/my-next-app"
      tag: latest
    labels: 
      app: next-app
    port : 3000
  service:
    type: LoadBalancer 
    port : 80
    labels:
      app: next-app