{{- with .Values.next-app.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ $.Release.Name }}-next-app
  labels: 
     app: {{ .labels.app }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .labels.app }}
  template:
    metadata:
      labels:
        app: {{ .labels.app }}
    spec:
      containers:
      - name: {{ $.Release.Name }}-next-app
        image: {{ .image.repository }}:{{ .image.tag }}
        ports:
        - containerPort: {{ .port }}
      imagePullSecrets:
        # - name: ghcr-secret       ## can be removed since image is in public registry
{{- end }}

