name: Deploy to EC2 Kubernetes Cluster

on:
  workflow_run:
    workflows: ["Node.js CI"] # This workflow will be triggered by "Build and Test"
    types:
      - completed
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy app
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          # kubectl rollout status deployment/my-app
