# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-docker-image:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/my-next-app:latest .

  trivy-scan:
    needs: build-docker-image
    runs-on: self-hosted
    steps:

      # Trivy Scan 
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/my-next-app:latest
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          vuln-type: 'os,library'

  push-docker-image:
    needs: trivy-scan
    runs-on: self-hosted
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT}}
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-next-app:latest


    

  # deploy_on_kubernetes:
  #   needs: push-docker-image
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Verify cluster access
  #       run: |
  #         kubectl cluster-info
  #         kubectl get nodes

  #     - name: Deploy app
  #       run: |
  #         kubectl apply -f k8s/deployment.yaml
  #         kubectl apply -f k8s/service.yaml

  helm-install-app:
    needs: push-docker-image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Helm Dry Run Install
        run: |
          helm install next-app1 ./helm-next-app 
