# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
#   build:
#     runs-on: self-hosted
#     strategy:
#       matrix:
#         node-version: [18.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: npm run build --if-present
#     - name: Verify .next exists
#       run: ls -la .next
#     - name: Debug check before upload
#       run: pwd && ls -la && ls -la .next
#     - name: Upload build output
#       uses: actions/upload-artifact@v4
#       with:
#         name: next-build
#         include-hidden-files: true
#         path: .next/
#         if-no-files-found: error
  # build-and-push:
  #   runs-on: self-hosted

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Log in to GHCR
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GH_PAT}}

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: true
  #         tags: |
  #           ghcr.io/${{ github.repository_owner }}/my-next-app:latest

  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install and auto-fix vulnerabilities before Docker build
      - name: Install dependencies and fix vulnerabilities
        run: |
          npm ci
          echo "Running npm audit fix..."
          npm audit fix || true
          echo "Verifying updated dependencies..."
          npm ls cross-spawn || true

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository_owner }}/my-next-app:latest .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/my-next-app:latest
          format: 'table'
          exit-code: '1'  # Fail workflow if vulnerabilities are found
          severity: 'CRITICAL'

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/my-next-app:latest


    

  deploy_on_kubernetes:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Deploy app
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

